# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetDacVoltage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SetDacVoltage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13SetDacVoltage.proto\"N\n\rSetDacVoltage\x12\x11\n\x06\x64\x61\x63_id\x18\x01 \x02(\x07:\x01\x30\x12\x16\n\x0b\x64\x61\x63_channel\x18\x02 \x02(\x07:\x01\x30\x12\x12\n\x07voltage\x18\x03 \x02(\x02:\x01\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SETDACVOLTAGE = _descriptor.Descriptor(
  name='SetDacVoltage',
  full_name='SetDacVoltage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dac_id', full_name='SetDacVoltage.dac_id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dac_channel', full_name='SetDacVoltage.dac_channel', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='SetDacVoltage.voltage', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['SetDacVoltage'] = _SETDACVOLTAGE

SetDacVoltage = _reflection.GeneratedProtocolMessageType('SetDacVoltage', (_message.Message,), dict(
  DESCRIPTOR = _SETDACVOLTAGE,
  __module__ = 'SetDacVoltage_pb2'
  # @@protoc_insertion_point(class_scope:SetDacVoltage)
  ))
_sym_db.RegisterMessage(SetDacVoltage)


# @@protoc_insertion_point(module_scope)
